import Category from "@/components/Category";
import Review from "@/components/Review";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "audiophile speakers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    return <div className="mt-[4rem]">{children}
        <Category />
        <Review/>
    </div>;
}
